Больше деталей
htmlacademy-univer-javascript-1/2579433-kekstagram-5 pull request #4
Opened 2024-11-27 13:08 UTC by Imb0duck

2024-12-03 10:45 UTC, dimohqa requested changes

2024-12-03 10:45 UTC, dimohqa commented on js/main.js
> +    const post = createPost(i, i);
А зачем два раза передавать одну переменную?

2024-12-03 10:45 UTC, dimohqa commented on js/main.js
> +    likes: Math.floor(generateRandom(15, 200)),
А зачем тут `Math.floor`?

2024-12-03 10:45 UTC, dimohqa commented on js/main.js
> +  const descriptions = ["Hope eradicated", "Meat automaton", "Divine light", "Power in misery", "CEO mindset", "Funny pills"];
Можно вынести в глобальную переменную `DESCRIPTIONS`

2024-12-03 10:45 UTC, dimohqa commented on js/main.js
> +  const max = generateRandom(0, 30);
А как ты работаешь с условием "Идентификаторы не должны повторяться"?

2024-12-03 11:47 UTC, Imb0duck commented on js/main.js
> +    const post = createPost(i, i);
url изначально планировал полную передавать

2024-12-03 11:51 UTC, Imb0duck commented on js/main.js
> +    likes: Math.floor(generateRandom(15, 200)),
Пропустил, когда убирал Math.floor

2024-12-03 11:52 UTC, Imb0duck commented on js/main.js
> +  const descriptions = ["Hope eradicated", "Meat automaton", "Divine light", "Power in misery", "CEO mindset", "Funny pills"];
Нужно ли, если массив используется только в этой функции?

2024-12-03 11:56 UTC, Imb0duck commented on js/main.js
> +  const max = generateRandom(0, 30);
Ставака была на то, чтоо если они генерируются через Date.now(), то повторятся не должны.

2024-12-03 19:55 UTC, Imb0duck commented on js/main.js
> +  const max = generateRandom(0, 30);
Могу усложнить формулу

2024-12-03 19:56 UTC, Imb0duck commented on js/main.js
> +  const max = generateRandom(0, 30);
Или проверка обязательна?

2024-12-04 07:37 UTC, dimohqa commented on js/main.js
> +  const max = generateRandom(0, 30);
Недоглядел, извиняюсь, все ок

2024-12-04 07:38 UTC, dimohqa commented on js/main.js
> +  const descriptions = ["Hope eradicated", "Meat automaton", "Divine light", "Power in misery", "CEO mindset", "Funny pills"];
Да, тут тонкое различие, но обычно константные данные стараются выносить из функций тк в будущем они могут быть переиспользованы. Можно не править, на будщее

2024-12-04 07:39 UTC, dimohqa approved these changes

2024-12-04 07:39 UTC, merged